### ISSUE TITLE
Start adding speakers to the website

### ISSUE THREAD

**Issue by kstracq** [LibertyJS/libertyjs-web2.0#108]
Anyone in highlighted in yellow is good to go, just turn them green as they get added:
https://docs.google.com/spreadsheets/d/1jBkWEgz_aqlD80lweNLNn-AO12WeINQgTAZVax1Yw-4/edit#gid=1611163900

Their papercall submission is attached to each speaker, fill out speaker.json with speaker and session. Make sure you connect speaker and session ids. Sandi Metz is a good template to use. Everything is local, so no need to touch the database.

Speaker photos: https://drive.google.com/drive/folders/14qksAW6JnFsAtWr7_s5eSQ3DeGFU-ygA

As of Sep 8, there are 9 speakers ready to be added

**Comment by nayonnapurnell** [comment]
The following speakers have been added on 9/23/2019
- Ron Lyle Dagdag
- Christina Deemer
- Fen Slattery
- Liz Krane

**Comment by nayonnapurnell** [comment]
The following speakers have been added on 9/24/2019
- Emily Rautenberg
- Viral Parmar
- Domitrius Clark

**Comment by nayonnapurnell** [comment]
@kstracq Do we have a picture for Mx. Kas Perch?

**Comment by kstracq** [comment]
I saw it in the google drive speakers photo folder last night, I’m pretty sure it’s the last one that was added

**Comment by nayonnapurnell** [comment]
@kstracq  I didn't see Mx. Kas Perch in the Google Doc.

**Comment by kstracq** [comment]
@nayonnapurnell i responded to you in slack:

https://drive.google.com/drive/folders/14qksAW6JnFsAtWr7_s5eSQ3DeGFU-ygA
labeled as kassian_wren

**Comment by nayonnapurnell** [comment]
9/26/201
- Added Mx. Kas Perch

@kstracq @che-effe I couldn't find angel rivera.  Do we have an image?

**Comment by kstracq** [comment]
angel and ali just dropped an image in. going to add now and then we have the full lineup up!!!
