### ISSUE TITLE
Team page

### ISSUE THREAD

**Issue by jennvoss** [LibertyJS/libertyjs-web2.0#11]
Each organizer needs to write their bio and choose a headshot.

**Comment by jennvoss** [comment]
No bios for now - we'll just put names & headshots on the team page

**Comment by beth-dickerson** [comment]
@jennvoss just an update: only waiting on a few headshots, so we're close!

**Comment by nayonnapurnell** [comment]
- Optimized each available headshot.

- Added each headshot to the default-firebase-data.json file.

**Comment by beth-dickerson** [comment]
@jennvoss I've combined the work for this issue and the one for updating the organizer photo into one PR

**Comment by beth-dickerson** [comment]
@jennvoss The only changes I have to add to the repo are headshot images. If we're going to use the images @nayonnapurnell added and optimized in the default-firebase-data.json file, should I just not worry about it?
Also, if so, then my changes have been completed for this issue, as they all took place in the firebase database!

**Comment by nayonnapurnell** [comment]
I added all the headshot images to images/team project folder.  I added all the social media links to each team member.
