### ISSUE TITLE
Add team photo to home page

### ISSUE THREAD

**Issue by jennvoss** [LibertyJS/libertyjs-web2.0#13]

**Comment by jennvoss** [comment]
Use this one: https://pbs.twimg.com/media/DrAxOq5XcAA0Pp2.jpg:large

**Comment by beth-dickerson** [comment]
@jennvoss I was working on this over the weekend and am struggling with the css for the pic. The picture shows up, but I'll show you what I'm talking about at lunch?

**Comment by beth-dickerson** [comment]
I believe this issue is also resolved, since the photo appears on the home page! (Did I forget to push it up, though?)
