### ISSUE TITLE
Remove the sign in feature from our nav

### ISSUE THREAD

**Issue by che-effe** [LibertyJS/libertyjs-web2.0#141]
This doesn't work and we're not going to need it.
![Screen Shot 2019-10-07 at 9 15 06 AM](https://user-images.githubusercontent.com/1616995/66315329-96fe9e00-e8e3-11e9-8a36-406cf518e814.png)

**Comment by Rob-Samalonis** [comment]
Should we also remove all code related to signing in, or just the option from the nav?

**Comment by che-effe** [comment]
at least the link for now, I don't think we'll ever need that feature, but I'll talk to the group at today's meeting to see if we'll ever have a need for it.

**Comment by jennvoss** [comment]
done https://github.com/LibertyJS/libertyjs-web2.0/pull/145

**Comment by chiefcll** [comment]
This is used for saving sessions that users might want to see. If you open the schedule and try to flag a session, it will ask you to sign in. Might just need a key to tie it to Auth with google for it to work properly.

**Comment by jennvoss** [comment]
created a new issue for saving sessions: https://github.com/LibertyJS/libertyjs-web2.0/issues/152

**Comment by Rob-Samalonis** [comment]
Fixed the nav through editing firebase / google cloud console settings. Going to re-add this sign in button.
