### ISSUE TITLE
Update tag in session to be "tools" not "toos"

### ISSUE THREAD

**Issue by kstracq** [LibertyJS/libertyjs-web2.0#144]
<img width="394" alt="Screen Shot 2019-10-07 at 12 08 04 PM" src="https://user-images.githubusercontent.com/2005569/66328727-2e232000-e8fb-11e9-9024-dd2676b10d30.png">

**Comment by jennvoss** [comment]
fixed in https://github.com/LibertyJS/libertyjs-web2.0/pull/149
