### ISSUE TITLE
Update tweet message hashtag to #LibertyJS2019

### ISSUE THREAD

**Issue by kstracq** [LibertyJS/libertyjs-web2.0#146]
<img width="653" alt="Screen Shot 2019-10-07 at 12 47 18 PM" src="https://user-images.githubusercontent.com/2005569/66331472-a3ddba80-e900-11e9-8b56-181c75bcf86e.png">

**Comment by jennvoss** [comment]
fixed in https://github.com/LibertyJS/libertyjs-web2.0/pull/150
