### ISSUE TITLE
Add 2018 highlights section

### ISSUE THREAD

**Issue by jennvoss** [LibertyJS/libertyjs-web2.0#22]
Upload photos to firebase (or connect to google photos if possible)

**Comment by jennvoss** [comment]
Reopening: needs to be redone since db was reset

**Comment by nayonnapurnell** [comment]
Hey where are we linking this from?

**Comment by kstracq** [comment]
@nayonnapurnell  is this issue complete? The photos are grabbed from here: https://photos.google.com/share/AF1QipOfC2CNlwXw-Gi-2Cefx23V9erOZAzIumlblSkUc9vc_5i4eL4721ZxNL9zOp64zw?key=ci1PWWgtVUVpbm9tMkhUTHlZWGFkTnNpQ1dHZGxB

**Comment by nayonnapurnell** [comment]
Are we adding the YouTube video to this section?  Do we want to add a highlights button to the home page?
