### ISSUE TITLE
Set up mailchimp

### ISSUE THREAD

**Issue by jennvoss** [LibertyJS/libertyjs-web2.0#8]

**Comment by chiefcll** [comment]
https://github.com/LibertyJS/libertyjs-web2.0/blob/master/docs/tutorials/mailchimp-autosubscribe.md

**Comment by jennvoss** [comment]
decided not to move forward with this since it requires a paid plan and we very infrequently send mailchimp campaigns. for now we will manually export the subscribers list from firebase
