### ISSUE TITLE
Add Sandi Metz to website

### ISSUE THREAD

**Issue by kstracq** [LibertyJS/libertyjs-web2.0#82]

**Comment by nayonnapurnell** [comment]
1) Did we add Sandi's image to the project folder?
2) Are we solely posting Sandi's name or additional information?

**Comment by kstracq** [comment]
i have a branch issue-82/sandimetz with her stuff filled out in the json and image in the image folder and i wanted to test it out on staging, but un sure how to move forward. chris said to use `npm run firestore:copy speakers backups/08-07-2018/speakers` but i don't really want to mess anything up

**Comment by nayonnapurnell** [comment]
Okay.  I always have to switch the items in development.json and production.json.
I do an npm build and then an npm deploy.

I didn't set up the development and production files.  Alex had pointed out when the site originally deployed that the staging site was pushing to production.

**Comment by nayonnapurnell** [comment]
Did you push your branch to the repo?

**Comment by nayonnapurnell** [comment]
I found it.

**Comment by kstracq** [comment]
I need help. I'm running `npm run serve:prod` to get liberty-js staging database, but no matter what i add to the database, i can't get sandi metz to show up as a speaker. im confused between speaker and generatedSpeaker, i added both to test though 🤷‍♀
