### ISSUE TITLE
Question: are the prod and dev json switched in config?

### ISSUE THREAD

**Issue by kstracq** [LibertyJS/libertyjs-web2.0#83]
shouldn't production be the site, and dev be staging?
<img width="1005" alt="Screen Shot 2019-06-11 at 9 18 40 PM" src="https://user-images.githubusercontent.com/2005569/59316882-9ab04a00-8c8e-11e9-9855-70cfe47676a4.png">

**Comment by nayonnapurnell** [comment]
Yes in theory production should be the site and dev should be staging but when the site went live, it was otherwise.

**Comment by nayonnapurnell** [comment]
In the docs/tutorials/deploy.md documentation it states to build with /config/devlopment.json
