### ISSUE TITLE
Add Comcast to sponsors

### ISSUE THREAD

**Issue by jennvoss** [LibertyJS/libertyjs-web2.0#88]

**Comment by nayonnapurnell** [comment]
Could you provide the Comcast logo that your marketing department uses for conferences?
@che-effe @kstracq  @alexclarkofficial @chiefcll

**Comment by che-effe** [comment]
@nayonnapurnell on it.

**Comment by che-effe** [comment]
This has been addressed with PR #90

**Comment by che-effe** [comment]
@nayonnapurnell ^ just wanted to make sure you saw this.
