### ISSUE TITLE
New blog post added to site

### ISSUE THREAD

**Issue by che-effe** [LibertyJS/libertyjs-web2.0#97]
new post from james available, please convert format to match our original blog post in html.
https://docs.google.com/document/d/1zOF3EoEYEd7z047rt3XljF0BBa1Bm9Y8Fkw0nLEsFdY/edit?usp=sharing
@nayonnapurnell

**Comment by nayonnapurnell** [comment]
Hey CF,

The blog post link is broken.  https://libertyjs.com/blog/posts/2019-sponsors/


![Screen Shot 2019-08-12 at 12 24 08 PM](https://user-images.githubusercontent.com/18585469/62880817-43653f00-bcfc-11e9-9f4d-b946651533a9.png)
